Repository adamstacey7/bp-two-team, pull requests merged in 2018-06, with the labels that each got.

#6 Feature/adding mirage
  .eslintrc.js
  app/adapters/application.js
  app/models/basic-details.js
  app/models/education.js
  app/models/professional-experience.js
  app/models/team-member.js
  app/models/team.js
  app/routes/index.js
  app/templates/application.hbs
  app/templates/index.hbs
  mirage/config.js
  mirage/scenarios/default.js
  mirage/serializers/application.js
  package-lock.json
  package.json
  tests/unit/adapters/application-test.js
  tests/unit/models/basic-details-test.js
  tests/unit/models/education-test.js
  tests/unit/models/professional-experience-test.js
  tests/unit/models/team-member-test.js
  tests/unit/models/team-test.js
  tests/unit/routes/index-test.js
Labels: Ready to merge

#15 Epic/setup mirage
  .eslintrc.js
  README.md
  app/adapters/application.js
  app/models/basic-details.js
  app/models/core-team-members.js
  app/models/education.js
  app/models/professional-experience.js
  app/models/team-member.js
  app/routes/index.js
  app/templates/application.hbs
  app/templates/index.hbs
  mirage/config.js
  mirage/scenarios/default.js
  mirage/serializers/application.js
  package-lock.json
  package.json
  tests/unit/adapters/application-test.js
  tests/unit/models/basic-details-test.js
  tests/unit/models/core-team-members.js
  tests/unit/models/education-test.js
  tests/unit/models/professional-experience-test.js
  tests/unit/models/team-member-test.js
  tests/unit/routes/index-test.js
Labels: Ready to merge

#21 #5 - adding in production heroku node express api baseurl
  app/adapters/application.js
  config/environment.js
Labels: review

#22 #17 - Added Bootstrap and Styling
  app/styles/app.less
  app/templates/index.hbs
  ember-cli-build.js
  package.json
Labels: review

#23 #17 - Added Bootstrap Stylings
  app/styles/app.less
  app/templates/index.hbs
  ember-cli-build.js
  package.json
Labels: Front end, review

#25 #11 - Create the create team member view with tests
  app/router.js
  app/routes/create-member.js
  app/templates/create-member.hbs
  tests/acceptance/create-member-test.js
  tests/unit/routes/create-member-test.js
Labels: review

#26 Feature/header component
  .gitignore
  app/adapters/application.js
  app/components/app-header.js
  app/controllers/application.js
  app/routes/core-team.js
  app/services/application.js
  app/styles/app.less
  app/templates/application.hbs
  app/templates/components/app-header.hbs
  app/templates/core-team.hbs
  app/templates/index.hbs
  config/environment.js
  ember-cli-build.js
  mirage/config.js
  package-lock.json
  package.json
  tests/integration/components/app-header-test.js
  tests/unit/controllers/application-test.js
  tests/unit/services/application-test.js
Labels: Front end, Ready to merge, review

#32 Feature/factories db refactor
  app/models/education.js
  app/models/experience.js
  app/routes/create-member.js
  app/templates/create-member.hbs
  app/templates/index.hbs
  mirage/config.js
  mirage/factories/education.js
  mirage/factories/experience.js
  mirage/factories/member.js
  mirage/models/education.js
  mirage/models/experience.js
  mirage/models/member.js
  mirage/scenarios/default.js
  mirage/serializers/member.js
  tests/acceptance/edit-member-test.js
Labels: review

#33 Feature/link to members page
  app/router.js
  app/routes/member.js
  app/routes/member/create.js
  app/routes/member/show.js
  app/routes/member/show/edit.js
  app/styles/app.less
  app/templates/core-team.hbs
  app/templates/create-member.hbs
  app/templates/index.hbs
  app/templates/member/create.hbs
  app/templates/member/show.hbs
  app/templates/member/show/edit.hbs
  tests/acceptance/core-team-test.js
  tests/acceptance/edit-member-test.js
  tests/acceptance/member-view-test.js
  tests/unit/routes/create-member-test.js
  tests/unit/routes/edit-member-test.js
  tests/unit/routes/member-test.js
  tests/unit/routes/member/create-test.js
  tests/unit/routes/member/show-test.js
  tests/unit/routes/member/show/edit-test.js
Labels: Ready to merge, review

#35 Feature/style view
  app/styles/app.less
  app/templates/components/team-list-item.hbs
  app/templates/member/show.hbs
  tests/acceptance/core-team-test.js
  tests/acceptance/member-view-test.js
  tests/integration/components/team-list-item-test.js
Labels: review

#36 Feature/add eslint prettier
  .eslintrc.js
  .eslintrc.json
  .prettierrc
  .vscode/launch.json
  app/app.js
  app/components/team-list-item.js
  app/router.js
  app/routes/member.js
  app/routes/member/create.js
  app/routes/member/show.js
  app/routes/member/show/edit.js
  app/routes/not-found.js
  config/environment.js
  ember-cli-build.js
  mirage/scenarios/default.js
  mirage/serializers/application.js
  package-lock.json
  package.json
  testem.js
  tests/acceptance/create-member-test.js
  tests/test-helper.js
  tests/unit/adapters/application-test.js
  tests/unit/models/education-test.js
  tests/unit/models/experience-test.js
  tests/unit/models/member-test.js
  tests/unit/routes/core-team-test.js
  tests/unit/routes/index-test.js
  tests/unit/routes/member-test.js
  tests/unit/routes/member/create-test.js
  tests/unit/routes/member/show-test.js
  tests/unit/routes/member/show/edit-test.js
  tests/unit/routes/not-found-test.js
Labels: Ready to merge, review

#37 #7 - add pre commit hooks
  package-lock.json
  package.json
Labels: Ready to merge, review

#38 Epic/implement linting
  .eslintrc.js
  .eslintrc.json
  .prettierrc
  .vscode/launch.json
  app/app.js
  app/components/team-list-item.js
  app/router.js
  app/routes/member.js
  app/routes/member/create.js
  app/routes/member/show.js
  app/routes/member/show/edit.js
  app/routes/not-found.js
  config/environment.js
  ember-cli-build.js
  mirage/scenarios/default.js
  mirage/serializers/application.js
  package-lock.json
  package.json
  testem.js
  tests/acceptance/create-member-test.js
  tests/test-helper.js
  tests/unit/adapters/application-test.js
  tests/unit/models/education-test.js
  tests/unit/models/experience-test.js
  tests/unit/models/member-test.js
  tests/unit/routes/core-team-test.js
  tests/unit/routes/index-test.js
  tests/unit/routes/member-test.js
  tests/unit/routes/member/create-test.js
  tests/unit/routes/member/show-test.js
  tests/unit/routes/member/show/edit-test.js
  tests/unit/routes/not-found-test.js
Labels: review

#41 Feature/remove core member
  app/components/team-list-item.js
  app/controllers/core-team.js
  app/templates/components/team-list-item.hbs
  app/templates/core-team.hbs
  mirage/config.js
  package-lock.json
  package.json
  tests/acceptance/core-team-test.js
  tests/integration/components/team-list-item-test.js
  tests/unit/controllers/core-team-test.js
Labels: Ready to merge, review

#42 #13 - got the ability to edit a team member workign with tests
  .eslintrc.json
  app/router.js
  app/routes/member/edit.js
  app/routes/member/show/edit.js
  app/templates/member/edit.hbs
  app/templates/member/show/edit.hbs
  tests/acceptance/edit-member-test.js
  tests/unit/routes/member/edit-test.js
  tests/unit/routes/member/show/edit-test.js
Labels: review

#44 Feature/create refactor
  app/routes/member/create.js
  app/templates/components/create-member-form.hbs
  app/templates/member/create.hbs
  package.json
  tests/unit/routes/member/create-test.js
  tests/unit/routes/member/edit-test.js
Labels: review

#47 Feature/confirmation message
  app/components/custom-alert.js
  app/components/team-list-item.js
  app/controllers/core-team.js
  app/styles/app.less
  app/templates/components/custom-alert.hbs
  app/templates/components/team-list-item.hbs
  app/templates/core-team.hbs
  mirage/scenarios/default.js
  tests/acceptance/core-team-test.js
  tests/acceptance/member-view-test.js
  tests/helpers/setupMockData.js
  tests/integration/components/custom-alert-test.js
  tests/integration/components/team-list-item-test.js
  tests/unit/controllers/core-team-test.js
Labels: Ready to merge, review

#49 Added the ability to add start date and end date
  app/templates/components/create-member-form.hbs
  app/templates/member/show.hbs
  package.json
Labels: review

#50 Epic/ability add dates
  app/templates/components/create-member-form.hbs
  app/templates/member/show.hbs
  package.json
Labels: review
